# Generated by Django 5.2.12 on 2026-03-11 22:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('title', models.CharField(help_text='Short description of what this task does.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional longer description.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current lifecycle state of this task.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='NORMAL', help_text='Execution priority.', max_length=10)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When this task should be executed.')),
                ('executed_at', models.DateTimeField(blank=True, help_text='When execution actually started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution finished (success or final failure).', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of execution attempts so far.')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts before marking as FAILED.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('celery_task_id', models.CharField(blank=True, default='', help_text='Celery async task ID for tracking.', max_length=255)),
                ('user', models.ForeignKey(help_text='The user who owns this task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('started_at', models.DateTimeField(help_text='When this execution attempt started.')),
                ('finished_at', models.DateTimeField(blank=True, help_text='When this execution attempt finished.', null=True)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('TIMEOUT', 'Timeout')], help_text='Result of this execution attempt.', max_length=10)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error traceback or message if this attempt failed.')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='How long this execution took in milliseconds.', null=True)),
                ('worker_id', models.CharField(blank=True, default='', help_text='Identifier of the Celery worker that ran this execution.', max_length=255)),
                ('task', models.ForeignKey(help_text='The task this execution belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task')),
            ],
            options={
                'db_table': 'task_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('message', models.TextField(help_text='Log message content.')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', help_text='Severity level of this log entry.', max_length=10)),
                ('task', models.ForeignKey(help_text='The task this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task')),
            ],
            options={
                'db_table': 'task_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'scheduled_at'], name='idx_task_status_scheduled'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', '-created_at'], name='idx_task_user_created'),
        ),
    ]
